<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "xml_sitemap"
 *
 * Auto generated by Extension Builder 2018-07-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SLUB Sitemap',
    'description' => 'SLUB Sitemap - yet another sitemap extension',
    'category' => 'services',
    'author' => 'Alexander Bigga',
    'author_email' => 'alexander.bigga@slub-dresden.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
